import type { CurrentUser, Kid, Post } from "./types";

export const currentUser: CurrentUser = {
  name: "Caro Giménez",
  role: "Maestra",
  room: "Sala Soles",
  initial: "C",
};

export const posts: Post[] = [
  {
    id: "post-1",
    type: "achievement",
    childNames: ["Mateo"],
    childInitials: ["M"],
    avatarBackgroundColors: ["bg-[#A9D9E8]"],
    avatarTextColors: ["text-[#1F7A93]"],
    publishedAt: "14:20",
    authorName: "Caro Giménez",
    isAuthor: true,
    recipients: ["familia de Mateo"],
    content:
      "¡Usó el orinal solito por primera vez! Estaba feliz de contárselo a todos. Un gran paso.",
    likesCount: 3,
    commentsCount: 1,
  },
  {
    id: "post-2",
    type: "activity",
    childNames: ["Mateo"],
    childInitials: ["M"],
    avatarBackgroundColors: ["bg-[#A9D9E8]"],
    avatarTextColors: ["text-[#1F7A93]"],
    publishedAt: "09:40",
    authorName: "Caro Giménez",
    isAuthor: true,
    recipients: ["familia de Mateo"],
    content:
      "Pintamos con témperas esta mañana. Mateo eligió el azul para todo y se concentró un montón mezclando colores.",
    photoPlaceholder: "Foto · pintando con témperas",
    likesCount: 5,
    commentsCount: 2,
  },
  {
    id: "post-3",
    type: "announcement",
    childNames: ["Anuncio general"],
    childInitials: ["A"],
    avatarBackgroundColors: ["bg-[#CCD8F4]"],
    avatarTextColors: ["text-[#4E72C8]"],
    publishedAt: "07:50",
    authorName: "Caro Giménez",
    isAuthor: true,
    recipients: ["toda la sala"],
    content:
      "El viernes salimos al parque por la mañana. Recuerden mandar gorra y una botellita de agua.",
    likesCount: 8,
    commentsCount: 0,
  },
];

export const kids: Kid[] = [
  {
    id: "1",
    name: "Mateo Fernández",
    initial: "M",
    age: "3 años",
    room: "Soles",
    birthDate: "12 mar 2022",
    admissionDate: "feb 2025",
    linkedParents: 2,
    allergy: "MANÍ",
    allergyNote: "Alergia al maní. Evitar frutos secos. Lleva inhalador en la mochila.",
    avatarBackgroundColor: "#A9D9E8",
    avatarTextColor: "#1F7A93",
    parents: [
      {
        id: "p1",
        name: "Lucía Fernández",
        initial: "L",
        relation: "Mamá",
        status: "active",
        avatarBackgroundColor: "#C9B6E8",
      },
      {
        id: "p2",
        name: "Diego Fernández",
        initial: "D",
        relation: "Papá",
        status: "pending",
        avatarBackgroundColor: "#A9C7E8",
      },
    ],
  },
  {
    id: "2",
    name: "Sofía Méndez",
    initial: "S",
    age: "2 años",
    room: "Soles",
    birthDate: "5 sep 2023",
    admissionDate: "mar 2025",
    linkedParents: 1,
    avatarBackgroundColor: "#F4B8CC",
    avatarTextColor: "#C44A7A",
    parents: [],
  },
  {
    id: "3",
    name: "Benjamín Ruiz",
    initial: "B",
    age: "3 años",
    room: "Soles",
    birthDate: "20 ene 2022",
    admissionDate: "feb 2025",
    linkedParents: 2,
    avatarBackgroundColor: "#B9DEC4",
    avatarTextColor: "#3E8B62",
    parents: [],
  },
  {
    id: "4",
    name: "Valentina Soto",
    initial: "V",
    age: "2 años",
    room: "Soles",
    birthDate: "7 abr 2023",
    admissionDate: "mar 2025",
    linkedParents: 0,
    avatarBackgroundColor: "#F4DC8E",
    avatarTextColor: "#9A7B1E",
    parents: [],
  },
  {
    id: "5",
    name: "Tomás Díaz",
    initial: "T",
    age: "3 años",
    room: "Soles",
    birthDate: "15 nov 2022",
    admissionDate: "feb 2025",
    linkedParents: 1,
    allergy: "LACTOSA",
    avatarBackgroundColor: "#C9B6E8",
    avatarTextColor: "#7B5FC0",
    parents: [],
  },
  {
    id: "6",
    name: "Emma Castro",
    initial: "E",
    age: "2 años",
    room: "Soles",
    birthDate: "3 jul 2023",
    admissionDate: "mar 2025",
    linkedParents: 1,
    avatarBackgroundColor: "#F4B8CC",
    avatarTextColor: "#C44A7A",
    parents: [],
  },
  {
    id: "7",
    name: "Lucas Romero",
    initial: "L",
    age: "3 años",
    room: "Soles",
    birthDate: "28 dic 2022",
    admissionDate: "feb 2025",
    linkedParents: 1,
    avatarBackgroundColor: "#A9D9E8",
    avatarTextColor: "#1F7A93",
    parents: [],
  },
  {
    id: "8",
    name: "Olivia Vega",
    initial: "O",
    age: "2 años",
    room: "Soles",
    birthDate: "19 oct 2023",
    admissionDate: "mar 2025",
    linkedParents: 1,
    avatarBackgroundColor: "#B9DEC4",
    avatarTextColor: "#3E8B62",
    parents: [],
  },
];